### ISSUE TITLE
Root Project Name

### ISSUE THREAD

**Issue by jeffbrown** [grails-profiles/base#1]
(copied from https://github.com/grails/grails-profile-repository/issues/87)

I think we should create a `settings.gradle` for newly created applications and plugins that assigns a value to `rootProject.name`.  As it is right now, the project name will default to the directory name, which is problematic in some scenarios.

```
grails create-app someapp
mv someapp someotherapp
cd someotherapp
./gradlew assemble
```

That will create `build/libs/someotherapp-0.1.war`.

If the newly created project included a `settings.gradle` file which looked like this:

```
rootProject.name='someapp'
```

I think that would be better.

**Comment by aadrian** [comment]
@jeffbrown @graemerocher was this issue lost? 
A `settings.gradle` file still does not seem to be present in https://github.com/grails-profiles/base/tree/master/skeleton

nor is there when creating a new project with `grails create-new` for Grails 3.3.3 .

Thank you!
