### ISSUE TITLE
7.0.1-SNAPSHOT  - unable to resolve class groovy.jmx.GroovyMBean

### ISSUE THREAD

**Issue by codeconsole** [grails-profiles/base#111]
Build broke with this commit 

https://github.com/grails-profiles/base/commit/97556d8ab129068ca33d7ab5989bd32edd99e655

```
Execution failed for task ':compileProfile'.
> startup failed:
  /home/runner/work/base/base/commands/stop-app.groovy: 5: unable to resolve class groovy.jmx.GroovyMBean
   @ line 5, column 1.
     import groovy.jmx.GroovyMBean
     ^
  
  1 error
```

**Comment by jamesfredley** [comment]
The recent grails-gradle-plugin changes had caused it to be needed for the build to succeed on 9/11 and then more recent changes broke it again.

Here are the two actions that ran successfully after that line was added, which was needed at that time.

https://github.com/grails-profiles/base/actions/runs/10820139605
https://github.com/grails-profiles/base/actions/runs/10820148942

Here is it failing before that lines was added
https://github.com/grails-profiles/base/actions/runs/10820061958/job/30019287165

**Comment by jamesfredley** [comment]
We need to stabilize grails-gradle-plugin and may need to undo a few recent changes, since it broke builds on other projects, like this one.

**Comment by jamesfredley** [comment]
This is going to be fixed on grails-gradle-plugin

**Comment by codeconsole** [comment]
@jamesfredley don’t you need some sort of reference to groovy-jmx in Groovy 4 to add that import?

**Comment by jamesfredley** [comment]
This is fixed by https://github.com/grails/grails-gradle-plugin/pull/333
