### ISSUE TITLE
Grails 7: Error running domain-class in no package 

### ISSUE THREAD

**Issue by arjangch** [grails-profiles/base#112]
**Description**
I can create a domain-calss without being in a package. However grails 7 creates a package named _@artifact.package.path@_ and placess class file in there.  And when i run grails it return error. 

**Steps to Reproduce**
Create a domain-class without package `./grailsw create-domain-class Myemployee`
Then run `./gradlew bootRun`

**Expected Behaviour**
This works in Grails 5 and 6 but not in grails 7

**Actual Behaviour**
it returns error message `/grails-app/domain/@artifact.package.path@/Myemployee.groovy: 1: Unexpected input: '@artifact.package' @ line 1, column 11.`

**Environment Information**
Operating System: Mac OS
Grails Version: 7
JDK Version: 22.0.2

**Comment by codeconsole** [comment]
You need 
```yml
grails:
    codegen:
        defaultPackage: website
```

in application.yml

**Comment by jamesfredley** [comment]
This will need to get fixed on https://github.com/grails/grails-forge

**Comment by jamesfredley** [comment]
Moved this issue over to https://github.com/grails/grails-forge/issues/374
