### ISSUE TITLE
Why prefer org.glassfish.web:el-impl?

### ISSUE THREAD

**Issue by todoubaba** [grails-profiles/base#13]
Why [Add el-impl as a runtime dependency](https://github.com/grails-profiles/base/commit/2dff5b265dc606dc719549b7f22a9905e3493c82)? 

An implementation has been contained in `org.springframework.boot:spring-boot-starter-tomcat`, which is  `tomcat-embed-el-8.5.15.jar!/org/apache/el/ExpressionFactoryImpl.class`.

**Comment by graemerocher** [comment]
It is an issue if you deploy as a war
