### ISSUE TITLE
Is it necessary to include grails.spring.transactionManagement.proxies?

### ISSUE THREAD

**Issue by todoubaba** [grails-profiles/base#14]
According to the http://docs.grails.org/latest/guide/upgrading.html section `Spring Proxies for Services No Longer Supported`, is it necessary to include [grails.spring.transactionManagement.proxies](
https://github.com/grails-profiles/base/blob/master/skeleton/grails-app/conf/application.yml#L7) in the `application.yml`?

**Comment by graemerocher** [comment]
No it isn't, can be removed
