### ISSUE TITLE
Continuous testing: Only changed tests?

### ISSUE THREAD

**Issue by sburnicki** [grails-profiles/base#7]
The `test-app` command reruns all the tests when started with `-continuous`. From my point of view, it would make sense for test files to only run the tests contained in the changed files. Is this a specific design decision, or would it be possible to change this behavior?

I have no idea if this is the right place to put this issue. If not, please tell me the correct place ;)

**Comment by sdelamo** [comment]
If I am correct _-continuous_ is using the Gradle continuous feature: 

> -t, --continuous (incubating)
> Enables continuous building - Gradle will automatically re-run when changes are detected.

That it is more a Gradle behaviour than a Grails 

This may be a useful post: 

http://mrhaki.blogspot.com.es/2015/08/gradle-goodness-using-continuous-build.html

**Comment by sburnicki** [comment]
From the (source)[https://github.com/grails-profiles/base/blob/master/commands/test-app.groovy#L73] it looks like the continuous parameter starts directory watching and explicitly runs tests.

I wonder if it was possible to tell if only test sources changed and rerun explicitly the contained tests. Would probably be a lot faster if you're writing/modifying tests.
